#!/usr/bin/env python3
"""Embed the curated design sources in the native design app."""
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
DESIGN = ROOT / "apps/zork-design-pc"
OUTPUT = ROOT / "crates/zork-gui/src/bin/design_pc/assets.rs"
manifest = json.loads((DESIGN / "assets/manifest.json").read_text())
paths = {
    item["path"]
    for item in manifest["items"]
    if item["path"].endswith((".svg", ".png")) and (DESIGN / item["path"]).is_file()
}
for group in ("previews", "motion", "wordmark", "archive/reference-captures"):
    paths.update(
        str(path.relative_to(DESIGN))
        for path in (DESIGN / group).rglob("*")
        if path.suffix in {".svg", ".png"}
    )
paths.add("mobile/zork-mobile-v1.png")
paths = sorted(paths)
lines = [
    "//! Generated by scripts/design-pc/generate_assets.py; design inputs stay in apps/zork-design-pc.",
    "use gpui::{AssetSource, Result, SharedString};",
    "use std::borrow::Cow;",
    "use zork_gui::assets::EmbeddedAssets;",
    "pub struct DesignAssets;",
    "impl AssetSource for DesignAssets {",
    "    fn load(&self, path: &str) -> Result<Option<Cow<'static, [u8]>>> {",
    "        let design: Option<&'static [u8]> = match path {",
]
for path in paths:
    lines.append(
        f'            "design/{path}" => Some(include_bytes!("../../../../../apps/zork-design-pc/{path}")),')
lines += [
    "            _ => None,",
    "        };",
    "        if let Some(bytes) = design { return Ok(Some(Cow::Borrowed(bytes))); }",
    "        EmbeddedAssets.load(path)",
    "    }",
    "    fn list(&self, path: &str) -> Result<Vec<SharedString>> {",
    "        EmbeddedAssets.list(path)",
    "    }",
    "}",
]
references = sorted(
    str(path.relative_to(DESIGN))
    for path in (DESIGN / "archive/reference-captures").glob("*.png")
)
lines.append("pub const REFERENCE_PATHS: &[&str] = &[")
lines.extend(f'    "{path}",' for path in references)
lines.append("];")
rendered = subprocess.run(
    ["rustfmt", "--edition", "2021", "--emit", "stdout"],
    input="\n".join(lines) + "\n",
    text=True,
    capture_output=True,
    check=True,
).stdout
if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
    OUTPUT.write_text(rendered)
print(f"Embedded {len(paths)} curated native design images")
